### ISSUE TITLE
New Case: Data is lost after saving [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#139]
- [ ] when a new case is created and data is entered immediately afterwards, the data is lost

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 The health facility selection bug is fixed now. In addition we have found the reason why data is lost during case creation. The problem goes down to a synchronization problem that will need some time to get properly fixed. For the pre-workshop please do the following: When a new case is created in the app just press the save button once. All data that is entered afterwards should be saved correctly.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Ok Martin, I will try it out. \thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Moved the health facility bug to #140

**Comment by MartinWahnschaffeSymeda** [comment]
We need to make sure that the mobile app can detect that the pulled case is the same that already exists on the device and has not been changed. Maybe use a checksum/hashcode (without the changedate).

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda We still have issues with the saving case data lost even after saving new case. SOS

**Comment by MateStrysewskeSym** [comment]
Next steps: check if form can be refreshed when new entity is pulled or brute force override existing entities when saving

**Comment by MartinWahnschaffeSymeda** [comment]
This is working now. For details see commit https://github.com/hzi-braunschweig/SORMAS-Open/commit/fb43943f60bade80951cdbebe3c3c2a74ecddb8b
For the pilot we need to do a proper merging whenever data is transfered between app and server.
